### ISSUE TITLE
Target Cities not functioning properly

### ISSUE THREAD

**Issue by aghArdeshir** [reaper47/ind-appointment-checker#4]
Hi. Thanks for this amazing bot :smiley: 

![image](https://user-images.githubusercontent.com/5755214/205750199-2e86466c-b82c-4ebb-ae07-5b6d8f3e0515.png)

As you see, in the picture above, I've set "IND Amsterdam as target city, but I still get notifications for everywhere else.

I tried all these combinations, but none of them seem to work:
```
TARGET_CITIES=Amsterdam
TARGET_CITIES=IND Amsterdam
TARGET_CITIES="Amsterdam"
TARGET_CITIES="IND Amsterdam"
```

Thank you so much :heart:

**Comment by reaper47** [comment]
Thank you for pointing this out! I will look into it once I've got time :)

**Comment by reaper47** [comment]
I am unable to reproduce the issue. Is it still sending notifications for multiple cities when you select "IND Amsterdam" as the target city? 

![Screenshot from 2023-01-16 10-02-13](https://user-images.githubusercontent.com/5367592/212638775-b201af78-689f-4b61-9da3-06ec4257dba5.png)

**Comment by aghArdeshir** [comment]
Hi. I am sorry but I no longer have the situation to reproduce this 😬 
Thanks for checking it out
